name: Release webcounter

on:
  release:
    types:
    - published

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: echo ${{ github.ref_name }}

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
    #     file: ./backend.dockerfile