name: Test Web Counter

# events
on:
  push:
    branches:
    - main

env:
  TEST: OK

jobs:

  # list of jobs
  unit-tests:
    # where our code will run, GitHub self-hosted runner
    runs-on: ubuntu-latest

    # list of steps

    steps:

    # 1 clone our code (checkout)
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: See files
      run: ls -lah

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python tests.py

  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Run integration test
      run: sleep 10

  build-push-docker-image:
    runs-on: ubuntu-latest

    needs:
    - unit-tests
    - integration-tests

    steps:
    - name: Fake docker build
      run: sleep 5


  # docker/login-action
  # docker/build-push-action
  # secrets.SECRET_NAME
  # ${{ github.sha }}



