name: Test Web Counter

# events
on:
  push:
    branches:
    - main

jobs:

  # list of jobs
  test:
    # where our code will run, GitHub self-hosted runner
    runs-on: ubuntu-latest

    # list of steps

    steps:

    # 1 clone our code (checkout)
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: See files
      run: xls -lah