name: Test Web Counter

# events
on:
  push:
    branches:
    - main

env:
  TEST: OK

jobs:

  # list of jobs
  unit-tests:
    # where our code will run, GitHub self-hosted runner
    runs-on: ubuntu-latest

    # list of steps

    steps:

    # 1 clone our code (checkout)
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: See files
      run: ls -lah

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python tests.py

  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Run integration test
      run: sleep 1

  build-push-docker-image:
    runs-on: ubuntu-latest

    needs:
    - unit-tests
    - integration-tests

    steps:
    # - name: Check secret
    #   run: echo ${{ secrets.DOCKERHUB_USERNAME }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

  # docker/login-action
  # docker/build-push-action
  # secrets.SECRET_NAME
  # ${{ github.sha }}



